extends Node

var original: Dictionary

func _ready() -> void:
	_test_validation_schema()
	original = GameSettings.active.duplicate(true)
	var original_scale := float(GameSettings.active["render_scale"])
	var original_gi := bool(GameSettings.active["gi_enabled"])
	var original_environment_preset := int(GameSettings.active["environment_preset"])
	var staged_environment_preset := (original_environment_preset + 1) % 3
	var staged_scale := 0.55 if not is_equal_approx(original_scale, 0.55) else 0.65

	GameSettings.begin_edit()
	GameSettings.set_pending("render_scale", staged_scale)
	GameSettings.set_pending("gi_enabled", not original_gi)
	GameSettings.set_pending("environment_preset", staged_environment_preset)
	var original_visualizer := bool(GameSettings.active["trick_visualizer_enabled"])
	GameSettings.set_pending("trick_visualizer_enabled", not original_visualizer)
	_check(is_equal_approx(float(GameSettings.active["render_scale"]), original_scale), "Editing pending settings changed active state")
	_check(bool(GameSettings.active["gi_enabled"]) == original_gi, "Editing GI changed active state")
	_check(int(GameSettings.active["environment_preset"]) == original_environment_preset, "Editing time of day changed active state")
	_check(bool(GameSettings.active["trick_visualizer_enabled"]) == original_visualizer, "Editing visualizer setting changed active state")
	_check(is_equal_approx(get_viewport().scaling_3d_scale, original_scale), "Editing pending settings changed renderer state")

	GameSettings.cancel_pending()
	_check(is_equal_approx(float(GameSettings.pending["render_scale"]), original_scale), "Cancel did not restore pending state")
	_check(bool(GameSettings.pending["gi_enabled"]) == original_gi, "Cancel did not restore GI pending state")
	_check(int(GameSettings.pending["environment_preset"]) == original_environment_preset, "Cancel did not restore time of day")
	_check(bool(GameSettings.pending["trick_visualizer_enabled"]) == original_visualizer, "Cancel did not restore visualizer setting")

	GameSettings.begin_edit()
	GameSettings.set_pending("render_scale", staged_scale)
	GameSettings.set_pending("gi_enabled", not original_gi)
	GameSettings.set_pending("environment_preset", staged_environment_preset)
	GameSettings.set_pending("anti_aliasing", 0 if int(GameSettings.active["anti_aliasing"]) != 0 else 1)
	GameSettings.set_pending("shadow_quality", 0 if int(GameSettings.active["shadow_quality"]) != 0 else 3)
	GameSettings.apply_pending()
	_check(is_equal_approx(float(GameSettings.active["render_scale"]), staged_scale), "Apply did not promote pending state")
	_check(bool(GameSettings.active["gi_enabled"]) != original_gi, "Apply did not promote GI state")
	_check(int(GameSettings.active["environment_preset"]) == staged_environment_preset, "Apply did not promote time of day")
	_check(is_equal_approx(get_viewport().scaling_3d_scale, staged_scale), "Apply did not change renderer scale")
	_check(get_viewport().use_taa == (int(GameSettings.active["anti_aliasing"]) > 0), "Apply did not update anti-aliasing")
	_check(int(GameSettings.active["shadow_quality"]) in [0, 3], "Apply did not promote shadow quality")
	_check(FileAccess.file_exists(GameSettings.CONFIG_PATH), "Applied settings were not persisted")

	GameSettings.begin_edit()
	GameSettings.set_pending("scaling_mode", 2)
	GameSettings.set_pending("fsr_sharpness", 0.6)
	GameSettings.set_pending("reflection_quality", 1)
	GameSettings.set_pending("hdr_output", true)
	GameSettings.apply_pending()
	_check(int(get_viewport().scaling_3d_mode) == 2, "Apply did not promote the upscaling mode")
	_check(is_equal_approx(get_viewport().fsr_sharpness, 0.6), "Apply did not promote FSR sharpness")
	_check(not get_viewport().use_taa, "FSR2 did not take over temporal anti-aliasing")
	_check(int(GameSettings.active["reflection_quality"]) == 1, "Apply did not promote reflection quality")
	_check(bool(GameSettings.active["hdr_output"]), "Apply did not promote HDR output")
	_check(get_viewport().use_hdr_2d, "Apply did not enable the HDR 2D pipeline")
	# The window request only runs on real displays; headless/dummy servers
	# warn and ignore it, so the readback is asserted there only.
	if not RuntimeEnvironment.is_headless():
		_check(get_window().hdr_output_requested, "Apply did not request HDR output on the window")

	GameSettings.active = {}
	GameSettings.pending = {}
	GameSettings.load_settings()
	_check(is_equal_approx(float(GameSettings.active["render_scale"]), staged_scale), "Saved value did not survive reload")
	_check(bool(GameSettings.active["gi_enabled"]) != original_gi, "Saved GI value did not survive reload")
	_check(int(GameSettings.active["environment_preset"]) == staged_environment_preset, "Saved time of day did not survive reload")
	_check(int(GameSettings.active["anti_aliasing"]) in [0, 1], "Saved anti-aliasing did not survive reload")
	_check(int(GameSettings.active["shadow_quality"]) in [0, 1, 2, 3], "Saved shadow quality did not survive reload")
	_check(int(GameSettings.active["scaling_mode"]) == 2, "Saved upscaling mode did not survive reload")
	_check(is_equal_approx(float(GameSettings.active["fsr_sharpness"]), 0.6), "Saved FSR sharpness did not survive reload")
	_check(int(GameSettings.active["reflection_quality"]) == 1, "Saved reflection quality did not survive reload")
	_check(bool(GameSettings.active["hdr_output"]), "Saved HDR output did not survive reload")

	GameSettings.pending = original.duplicate(true)
	GameSettings.apply_pending()
	AudioManager.shutdown_audio()
	print("SETTINGS_PASS: pending, Cancel, Apply, renderer update, AA/shadow, validation, and persistence checks passed")
	get_tree().quit(0)

func _test_validation_schema() -> void:
	_check(GameSettings._validated("display_mode", -1) == 0, "Display mode did not clamp to the lower bound")
	_check(GameSettings._validated("display_mode", 99) == 2, "Display mode did not clamp to the upper bound")
	_check(GameSettings._validated("vsync_mode", -1) == 0, "VSync did not clamp to the lower bound")
	_check(GameSettings._validated("vsync_mode", 99) == 2, "VSync did not clamp to the upper bound")
	_check(is_equal_approx(float(GameSettings._validated("render_scale", 0.1)), 0.5), "Render scale did not clamp to the lower bound")
	_check(is_equal_approx(float(GameSettings._validated("render_scale", 1.9)), 1.5), "Render scale did not clamp to the upper bound")
	_check(is_equal_approx(float(GameSettings._validated("master_volume_db", -99.0)), -30.0), "Master volume did not clamp to the UI range")
	_check(is_equal_approx(float(GameSettings._validated("music_volume_db", 10.0)), 0.0), "Music volume did not clamp to the UI range")
	_check(GameSettings._validated("resolution", Vector2i(1, 99999)) == Vector2i(960, 4320), "Resolution did not clamp each axis to the safe range")
	_check(GameSettings._validated("ssao_enabled", "true") == GameSettings.DEFAULTS["ssao_enabled"], "Malformed boolean did not fall back to its default")
	_check(GameSettings._validated("gi_enabled", "true") == GameSettings.DEFAULTS["gi_enabled"], "Malformed GI boolean did not fall back to its default")
	_check(GameSettings._validated("hdr_output", "true") == GameSettings.DEFAULTS["hdr_output"], "Malformed HDR boolean did not fall back to its default")
	_check(GameSettings._validated("environment_preset", -1) == 0, "Time of day did not clamp to Day")
	_check(GameSettings._validated("environment_preset", 99) == 2, "Time of day did not clamp to Sunset")
	_check(GameSettings._validated("display_mode", "fullscreen") == GameSettings.DEFAULTS["display_mode"], "Malformed integer did not fall back to its default")
	_check(GameSettings._validated("resolution", Vector2(1920, 1080)) == GameSettings.DEFAULTS["resolution"], "Malformed resolution type did not fall back to its default")
	_check(GameSettings._validated("render_scale", INF) == GameSettings.DEFAULTS["render_scale"], "Non-finite numeric value did not fall back to its default")
	var missing_defaults := GameSettings._validated_settings({"render_scale": 0.75})
	_check(missing_defaults.size() == GameSettings.DEFAULTS.size(), "Missing settings keys were not restored from defaults")
	_check(missing_defaults["resolution"] == GameSettings.DEFAULTS["resolution"] and missing_defaults["fog_enabled"] == GameSettings.DEFAULTS["fog_enabled"] and missing_defaults["gi_enabled"] == GameSettings.DEFAULTS["gi_enabled"], "Missing settings values did not use defaults")
	GameSettings.apply_preset(1)
	_check(not bool(GameSettings.pending["gi_enabled"]), "Medium preset did not disable GI")
	GameSettings.apply_preset(2)
	_check(bool(GameSettings.pending["gi_enabled"]), "High preset did not allow GI")
	GameSettings.apply_preset(99)
	_check(int(GameSettings.pending["graphics_preset"]) == 4, "Invalid graphics preset did not clamp safely")
	GameSettings.apply_preset(0)
	_check(int(GameSettings.pending["reflection_quality"]) == 0, "Low preset did not select low reflections")
	GameSettings.apply_preset(1)
	_check(int(GameSettings.pending["reflection_quality"]) == 1, "Medium preset did not select medium reflections")
	GameSettings.apply_preset(2)
	_check(int(GameSettings.pending["reflection_quality"]) == 2, "High preset did not select high reflections")
	_check(int(GameSettings.pending["scaling_mode"]) == 0, "High preset did not reset the upscaling mode")
	var save_events := [0]
	var on_settings_saved := func() -> void: save_events[0] += 1
	GameSettings.settings_saved.connect(on_settings_saved)
	var normal_save_error := GameSettings.save_settings()
	GameSettings.settings_saved.disconnect(on_settings_saved)
	_check(normal_save_error == OK, "Normal settings save did not return OK")
	_check(save_events[0] == 1, "Normal settings save did not emit its success signal")
	var active_before_failure := GameSettings.active.duplicate(true)
	var save_failures: Array[Error] = []
	var on_save_failed := func(error: Error) -> void: save_failures.append(error)
	GameSettings.settings_save_failed.connect(on_save_failed)
	var save_error := GameSettings.save_settings("res://tests", false)
	GameSettings.settings_save_failed.disconnect(on_save_failed)
	_check(save_error != OK, "Invalid settings path unexpectedly reported success")
	_check(save_failures.size() == 1 and save_failures[0] == save_error, "Settings save failure was not reported through its signal")
	_check(GameSettings.active == active_before_failure, "Failed settings save rolled back or changed active settings")
	_check(GameSettings._validated("scaling_mode", -1) == 0, "Upscaling mode did not clamp to the lower bound")
	_check(GameSettings._validated("scaling_mode", 99) == 2, "Upscaling mode did not clamp to the upper bound")
	_check(is_equal_approx(float(GameSettings._validated("fsr_sharpness", -1.0)), 0.0), "FSR sharpness did not clamp to the lower bound")
	_check(is_equal_approx(float(GameSettings._validated("fsr_sharpness", 5.0)), 2.0), "FSR sharpness did not clamp to the upper bound")

func _check(condition: bool, message: String) -> void:
	if not condition:
		push_error("SETTINGS_FAIL: " + message)
		AudioManager.shutdown_audio()
		get_tree().quit(1)
