class_name SkierAnimationFrame
extends RefCounted

enum TakeoffType { NONE, CHARGED_POP, TERRAIN_TAKEOFF }

var locomotion_state: int = 0
var speed_mps: float = 0.0
var speed_ratio: float = 0.0
var edge: float = 0.0
var turn_input: float = 0.0
var turn_rate: float = 0.0
var skid: float = 0.0
var skid_ratio: float = 0.0
var carve_force: float = 0.0
var lateral_acceleration: float = 0.0
var carve_ratio: float = 1.0
var heading_velocity_delta: float = 0.0
var skier_heading: Vector3 = Vector3.FORWARD
var velocity_heading: Vector3 = Vector3.FORWARD
var slope_angle: float = 0.0
var grounded: bool = false
var tuck: float = 0.0
var braking: bool = false
var compression: float = 0.0
var contact_confidence: float = 0.0
var ground_normal: Vector3 = Vector3.UP
var seat_distance: float = 0.54
var left_ground_distance: float = 0.54
var right_ground_distance: float = 0.54
var left_normal: Vector3 = Vector3.UP
var right_normal: Vector3 = Vector3.UP
var left_hit_position: Vector3 = Vector3.ZERO
var right_hit_position: Vector3 = Vector3.ZERO
var left_grounded: bool = false
var right_grounded: bool = false
var left_contact_confidence: float = 0.0
var right_contact_confidence: float = 0.0
var left_front_valid: bool = false
var left_rear_valid: bool = false
var right_front_valid: bool = false
var right_rear_valid: bool = false
var left_front_position: Vector3 = Vector3.ZERO
var left_rear_position: Vector3 = Vector3.ZERO
var right_front_position: Vector3 = Vector3.ZERO
var right_rear_position: Vector3 = Vector3.ZERO
var left_front_normal: Vector3 = Vector3.UP
var left_rear_normal: Vector3 = Vector3.UP
var right_front_normal: Vector3 = Vector3.UP
var right_rear_normal: Vector3 = Vector3.UP
var angular_velocity: Vector3 = Vector3.ZERO
var vertical_velocity: float = 0.0
var air_time: float = 0.0
var takeoff_type: int = TakeoffType.NONE
var takeoff_charge: float = 0.0
var takeoff_upward_speed: float = 0.0
var air_upward_velocity: float = 0.0
var predicted_landing_time: float = -1.0
var grab_pose: int = 0
var switch_stance: bool = false
var rail_speed: float = 0.0
var rail_balance: float = 0.0
var rail_type: int = 0
var trick_kind: int = 0
var trick_phase: int = 0
var gesture_strength: float = 0.0
var gesture_direction: Vector2 = Vector2.ZERO
var left_trigger: float = 0.0
var right_trigger: float = 0.0
var grab_amount: float = 0.0
var grab_tweak: Vector2 = Vector2.ZERO
var rotation_progress: float = 0.0

func reset() -> void:
	locomotion_state = 0
	speed_mps = 0.0
	speed_ratio = 0.0
	edge = 0.0
	turn_input = 0.0
	turn_rate = 0.0
	skid = 0.0
	skid_ratio = 0.0
	carve_force = 0.0
	lateral_acceleration = 0.0
	carve_ratio = 1.0
	heading_velocity_delta = 0.0
	skier_heading = Vector3.FORWARD
	velocity_heading = Vector3.FORWARD
	slope_angle = 0.0
	grounded = false
	tuck = 0.0
	braking = false
	compression = 0.0
	contact_confidence = 0.0
	ground_normal = Vector3.UP
	seat_distance = 0.54
	left_ground_distance = 0.54
	right_ground_distance = 0.54
	left_normal = Vector3.UP
	right_normal = Vector3.UP
	left_hit_position = Vector3.ZERO
	right_hit_position = Vector3.ZERO
	left_grounded = false
	right_grounded = false
	left_contact_confidence = 0.0
	right_contact_confidence = 0.0
	left_front_valid = false
	left_rear_valid = false
	right_front_valid = false
	right_rear_valid = false
	left_front_position = Vector3.ZERO
	left_rear_position = Vector3.ZERO
	right_front_position = Vector3.ZERO
	right_rear_position = Vector3.ZERO
	left_front_normal = Vector3.UP
	left_rear_normal = Vector3.UP
	right_front_normal = Vector3.UP
	right_rear_normal = Vector3.UP
	angular_velocity = Vector3.ZERO
	vertical_velocity = 0.0
	air_time = 0.0
	takeoff_type = TakeoffType.NONE
	takeoff_charge = 0.0
	takeoff_upward_speed = 0.0
	air_upward_velocity = 0.0
	predicted_landing_time = -1.0
	grab_pose = 0
	switch_stance = false
	rail_speed = 0.0
	rail_balance = 0.0
	rail_type = 0
	trick_kind = 0
	trick_phase = 0
	gesture_strength = 0.0
	gesture_direction = Vector2.ZERO
	left_trigger = 0.0
	right_trigger = 0.0
	grab_amount = 0.0
	grab_tweak = Vector2.ZERO
	rotation_progress = 0.0
