class_name SkierAnimationFrame
extends RefCounted

enum TakeoffType { NONE, CHARGED_POP, TERRAIN_TAKEOFF }

var locomotion_state: int = 0
var speed_mps: float = 0.0
var speed_ratio: float = 0.0
var edge: float = 0.0
var turn_input: float = 0.0
var turn_rate: float = 0.0
var skid: float = 0.0
var skid_ratio: float = 0.0
var carve_force: float = 0.0
var lateral_acceleration: float = 0.0
var carve_ratio: float = 1.0
var heading_velocity_delta: float = 0.0
var skier_heading: Vector3 = Vector3.FORWARD
var velocity_heading: Vector3 = Vector3.FORWARD
var slope_angle: float = 0.0
var grounded: bool = false
var tuck: float = 0.0
var braking: bool = false
var compression: float = 0.0
var contact_confidence: float = 0.0
var ground_normal: Vector3 = Vector3.UP
var seat_distance: float = 0.54
var left_ground_distance: float = 0.54
var right_ground_distance: float = 0.54
var left_normal: Vector3 = Vector3.UP
var right_normal: Vector3 = Vector3.UP
var left_hit_position: Vector3 = Vector3.ZERO
var right_hit_position: Vector3 = Vector3.ZERO
var left_grounded: bool = false
var right_grounded: bool = false
var left_contact_confidence: float = 0.0
var right_contact_confidence: float = 0.0
var left_front_valid: bool = false
var left_rear_valid: bool = false
var right_front_valid: bool = false
var right_rear_valid: bool = false
var left_front_position: Vector3 = Vector3.ZERO
var left_rear_position: Vector3 = Vector3.ZERO
var right_front_position: Vector3 = Vector3.ZERO
var right_rear_position: Vector3 = Vector3.ZERO
var left_front_normal: Vector3 = Vector3.UP
var left_rear_normal: Vector3 = Vector3.UP
var right_front_normal: Vector3 = Vector3.UP
var right_rear_normal: Vector3 = Vector3.UP
## Body-local Euler-rate telemetry used by trick/residual presentation.
var angular_velocity: Vector3 = Vector3.ZERO
## World-space angular telemetry; landing projection only. Never substitute for local rates.
var angular_velocity_world: Vector3 = Vector3.ZERO
var angular_velocity_world_valid: bool = true
## Gameplay body/ski axes, kept separate from the visual rig pose.
var body_up: Vector3 = Vector3.UP
var body_up_valid: bool = true
var ski_forward: Vector3 = Vector3.FORWARD
var ski_forward_valid: bool = true
var ski_up: Vector3 = Vector3.UP
var ski_up_valid: bool = true
var vertical_velocity: float = 0.0
var air_time: float = 0.0
var takeoff_type: int = TakeoffType.NONE
var takeoff_charge: float = 0.0
var takeoff_upward_speed: float = 0.0
var air_upward_velocity: float = 0.0
var predicted_landing_time: float = -1.0
var predicted_landing_normal: Vector3 = Vector3.UP
var predicted_landing_point: Vector3 = Vector3.ZERO
var predicted_landing_valid: bool = false
var landing_impact_speed: float = 0.0
var landing_impact_severity: float = 0.0
var landing_balance_error: float = 0.0
var landing_ski_alignment_error: float = 0.0
var landing_body_roll_error: float = 0.0
var landing_body_pitch_error: float = 0.0
var landing_rotation_error: float = 0.0
var landing_lateral_velocity: float = 0.0
var landing_forward_velocity: float = 0.0
var landing_air_time: float = 0.0
var landing_surface_normal: Vector3 = Vector3.UP
var landing_outcome: int = 0
var landing_event_active: bool = false
var grab_pose: int = 0
var style_pose: int = 0
var style_amount: float = 0.0
var switch_stance: bool = false
var rail_speed: float = 0.0
var rail_balance: float = 0.0
var rail_type: int = 0
var rail_pose: int = 0
var rail_direction: Vector3 = Vector3.FORWARD
var rail_up: Vector3 = Vector3.UP
var rail_contact_point: Vector3 = Vector3.ZERO
var rail_contact_valid: bool = false
var rail_slope: float = 0.0
var rail_kink_severity: float = 0.0
var rail_balance_velocity: float = 0.0
var rail_entry_direction: Vector3 = Vector3.FORWARD
var rail_exit_direction: Vector3 = Vector3.FORWARD
var rail_progress: float = 0.0
var rail_distance_to_end: float = 999.0
var rail_entry_severity: float = 0.0
var rail_approach_anticipation: float = 0.0
var left_ski_target_world: Transform3D = Transform3D.IDENTITY
var right_ski_target_world: Transform3D = Transform3D.IDENTITY
var left_ski_target_valid: bool = false
var right_ski_target_valid: bool = false
var trick_kind: int = 0
var trick_phase: int = 0
var gesture_strength: float = 0.0
var gesture_direction: Vector2 = Vector2.ZERO
var left_trigger: float = 0.0
var right_trigger: float = 0.0
var grab_amount: float = 0.0
var grab_tweak: Vector2 = Vector2.ZERO
var grab_input_strength: float = 0.0
var grab_hold_time: float = 0.0
var grab_release_time: float = 0.0
var rotation_progress: float = 0.0
var trick_active: bool = false
var trick_intent: bool = false
var rotation_accumulated: Vector3 = Vector3.ZERO
var rotation_residual: Vector3 = Vector3.ZERO
var rotation_axis_local: Vector3 = Vector3.ZERO
var rotation_axis_weights: Vector3 = Vector3.ZERO
## Gameplay-owned body shape and effective rotational inertia. Presentation
## reads these values but never writes rotation back to gameplay.
var rotation_compactness: float = 0.5
var rotation_inertia_scale: float = 1.0
var crash_reason: int = CrashContext.Reason.NONE
var crash_stage: int = CrashContext.Stage.NONE
var crash_elapsed: float = 0.0
var crash_stage_elapsed: float = 0.0
var crash_stage_progress: float = 0.0
var crash_impact_normal: Vector3 = Vector3.UP
var crash_incoming_velocity: Vector3 = Vector3.ZERO
var crash_current_velocity: Vector3 = Vector3.ZERO
var crash_impact_speed: float = 0.0
var crash_lateral_bias: float = 0.0
var crash_angular_speed: float = 0.0
var crash_rest_detected: bool = false
var pre_bail_weight: float = 0.0
var pre_bail_side: float = 0.0

func reset() -> void:
	locomotion_state = 0
	speed_mps = 0.0
	speed_ratio = 0.0
	edge = 0.0
	turn_input = 0.0
	turn_rate = 0.0
	skid = 0.0
	skid_ratio = 0.0
	carve_force = 0.0
	lateral_acceleration = 0.0
	carve_ratio = 1.0
	heading_velocity_delta = 0.0
	skier_heading = Vector3.FORWARD
	velocity_heading = Vector3.FORWARD
	slope_angle = 0.0
	grounded = false
	tuck = 0.0
	braking = false
	compression = 0.0
	contact_confidence = 0.0
	ground_normal = Vector3.UP
	seat_distance = 0.54
	left_ground_distance = 0.54
	right_ground_distance = 0.54
	left_normal = Vector3.UP
	right_normal = Vector3.UP
	left_hit_position = Vector3.ZERO
	right_hit_position = Vector3.ZERO
	left_grounded = false
	right_grounded = false
	left_contact_confidence = 0.0
	right_contact_confidence = 0.0
	left_front_valid = false
	left_rear_valid = false
	right_front_valid = false
	right_rear_valid = false
	left_front_position = Vector3.ZERO
	left_rear_position = Vector3.ZERO
	right_front_position = Vector3.ZERO
	right_rear_position = Vector3.ZERO
	left_front_normal = Vector3.UP
	left_rear_normal = Vector3.UP
	right_front_normal = Vector3.UP
	right_rear_normal = Vector3.UP
	angular_velocity = Vector3.ZERO
	angular_velocity_world = Vector3.ZERO
	angular_velocity_world_valid = true
	body_up = Vector3.UP
	body_up_valid = true
	ski_forward = Vector3.FORWARD
	ski_forward_valid = true
	ski_up = Vector3.UP
	ski_up_valid = true
	vertical_velocity = 0.0
	air_time = 0.0
	takeoff_type = TakeoffType.NONE
	takeoff_charge = 0.0
	takeoff_upward_speed = 0.0
	air_upward_velocity = 0.0
	predicted_landing_time = -1.0
	predicted_landing_normal = Vector3.UP
	predicted_landing_point = Vector3.ZERO
	predicted_landing_valid = false
	landing_impact_speed = 0.0
	landing_impact_severity = 0.0
	landing_balance_error = 0.0
	landing_ski_alignment_error = 0.0
	landing_body_roll_error = 0.0
	landing_body_pitch_error = 0.0
	landing_rotation_error = 0.0
	landing_lateral_velocity = 0.0
	landing_forward_velocity = 0.0
	landing_air_time = 0.0
	landing_surface_normal = Vector3.UP
	landing_outcome = 0
	landing_event_active = false
	grab_pose = 0
	style_pose = 0
	style_amount = 0.0
	switch_stance = false
	rail_speed = 0.0
	rail_balance = 0.0
	rail_type = 0
	rail_pose = 0
	rail_direction = Vector3.FORWARD
	rail_up = Vector3.UP
	rail_contact_point = Vector3.ZERO
	rail_contact_valid = false
	rail_slope = 0.0
	rail_kink_severity = 0.0
	rail_balance_velocity = 0.0
	rail_entry_direction = Vector3.FORWARD
	rail_exit_direction = Vector3.FORWARD
	rail_progress = 0.0
	rail_distance_to_end = 999.0
	rail_entry_severity = 0.0
	rail_approach_anticipation = 0.0
	left_ski_target_world = Transform3D.IDENTITY
	right_ski_target_world = Transform3D.IDENTITY
	left_ski_target_valid = false
	right_ski_target_valid = false
	trick_kind = 0
	trick_phase = 0
	gesture_strength = 0.0
	gesture_direction = Vector2.ZERO
	left_trigger = 0.0
	right_trigger = 0.0
	grab_amount = 0.0
	grab_tweak = Vector2.ZERO
	grab_input_strength = 0.0
	grab_hold_time = 0.0
	grab_release_time = 0.0
	rotation_progress = 0.0
	trick_active = false
	trick_intent = false
	rotation_accumulated = Vector3.ZERO
	rotation_residual = Vector3.ZERO
	rotation_axis_local = Vector3.ZERO
	rotation_axis_weights = Vector3.ZERO
	rotation_compactness = 0.5
	rotation_inertia_scale = 1.0
	crash_reason = CrashContext.Reason.NONE
	crash_stage = CrashContext.Stage.NONE
	crash_elapsed = 0.0
	crash_stage_elapsed = 0.0
	crash_stage_progress = 0.0
	crash_impact_normal = Vector3.UP
	crash_incoming_velocity = Vector3.ZERO
	crash_current_velocity = Vector3.ZERO
	crash_impact_speed = 0.0
	crash_lateral_bias = 0.0
	crash_angular_speed = 0.0
	crash_rest_detected = false
	pre_bail_weight = 0.0
	pre_bail_side = 0.0
